name: test-ubuntu
on: [push]
jobs:
  Test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: get nasm
        run: sudo apt-get install -y nasm
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Excecute tests
        run: make test
        run: ./a.out