name: test
on: [push]
jobs:
  Test-macos:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: get nasm
        run: brew install nasm
      - name: Compile
        run: make test
      - name: Excecute tests
        run: ./a.out
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: get nasm
        run: sudo apt-get install -y nasm
      - name: Compile
        run: make test
      - name: Excecute tests
        run: ./a.out
      - uses: actions/cache@v2
        with:
          path: |
            srcs
          key: ${{ runner.os }}-${{ hashFiles(srcs/*) }}
