name: test-macos
on: [push]
jobs:
  Test-macos:
    runs-on: macos-11
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: get homebrew
        run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
      - name: get nasm
        run: brew install nasm
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Excecute tests
        run: make test && ./a.out